LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Number is too big!"), "你輸入的數字過大!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Amount is too large"), "你輸入的數量過大");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Please give me a valid crate"), "請給我一個有效的箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Amount cannot be less than 1"), "數量不能少於 1");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Crate> crate does not exist"), "<Crate> 箱不存在");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Current crates: Mythic, Legendary, Rare, Uncommon, Common"), "目前箱: 神秘, 傳説, 稀有, 不常見, 常見");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Crate> is not for sale"), "<Crate> 箱不設販售");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not have enough money to buy <Amount> <Crate> crates\n\nYou need <NeededAmount>"), "你沒有足夠的金錢去購買<Amount> <Crate> 箱\n\你需要 <NeededAmount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not have enough money to buy <Amount> <Crate> crate\n\nYou need <NeededAmount>"), "你沒有足夠的金錢去購買<Amount> <Crate> 箱\n\你需要");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You cannot have more than 999,999,999 crates"), "你不能擁有超過 999,999,999 箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You just bought <Amount> <Crate> crates"), "你剛剛購買了 <Amount> <Crate> 箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You just bought <Amount> <Crate> crate"), "你剛剛購買了 <Amount> <Crate> 箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Please give me a valid Amount/Item"), "請給我一個有效的數量/物品");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You can't donate to yourself"), "你不能自己贊助");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Failed to parse string"), "不能成功解析");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not have enough money to donate <Amount> You only have <Bal>"), "你沒有足夠金錢去贊助 <Amount> 你只有 <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have successfully given <User> <Amount>"), "你已成功給予<User> <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Give me a valid food name"), "請給我一個有效的食物名稱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You are already at the max health <MaxHealth>"), "你已經達到滿血 <MaxHealth>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You just ate an <Food> and you are now at <Health>"), "你剛剛吃了 <Food> 你的血量達到了 <Health>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You just ate a <Food> and you are now at <Health>"), "你剛剛吃了 <Food> 你的血量達到了 <Health>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have <Owned> <Food> left"), "你擁有 <Owned> <Food> ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You just went fishing and came back with a <Food>"), "你剛剛去釣魚並拿著 <Food> 回來");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You just went fishing and came back with an <Food>"), "你剛剛去釣魚並拿著 <Food> 回來");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You just caught a <Food> in the wilderness"), "你剛剛在大自然抓了 <Food> ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You just caught an <Food> in the wilderness"), "你剛剛在大自然抓了 <Food> ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not have anything in your inventory"), "你的背包沒有任何物品");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "They do not have anything in their inventory"), "他們的背包沒有任何物品");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You can only open 10 crates at a time"), "你只能同時開啟 10 個箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not own any <Crate> crates"), "你沒有擁有任何 <Crate> 的箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not have enough crates to open <Amount>, you only have <Owned>"), "你沒有足夠的箱去開啟, 你只擁有 <Owned>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Please give me a valid weapon"), "請給予我一個有效的武器");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You cannot shoot yourself"), "你不能射自己");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Weapon> does not exist"), "<Weapon> 不存在");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not own any <Weapon>'s"), "你沒有擁有任何 <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "This weapon is a knife, Not a gun"), "此物品是刀, 不是槍");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "To use this weapon appropriately use <Shoot>"), "正確使用此武器請使用 <Shoot>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Health Before"), "之前的血量");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Health After"), "之後的血量");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Money Lost"), "失去金錢");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You cannot have more than the max bal in your wallet"), "你不能在錢包裏擁有超過最高上限的金錢");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "The weapon has reached max uses and has been destroyed"), "此武器達到最高使用上限次數並破壞了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have been killed"), "你已被殺死");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "User that killed you"), "你被殺死的用戶");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just took 50% of your money <MoneyTaken>"), "<User> 剛剛拿取了你金錢的50%， <MoneyTaken>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> had a bounty of <Bounty> and it has been collected by <User>"), "<User> 身上有<Bounty>的懸賞並被<User>領取了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just shot <User> with a <Weapon>"), "<User> 剛剛使用 <Weapon> 射死了 <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just shot <User> with a <Weapon> and died"), "<User> 剛剛使用 <Weapon> 射死了 <User> 並死亡了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just shot <User> with an <Weapon>"), "<User> 剛剛使用 <Weapon> 射死了 <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just shot <User> with an <Weapon> and died"), "<User> 剛剛使用 <Weapon> 射死了 <User> 並死亡了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You used this weapon more than it's intended use! This weapon has been deleted from your inventory"), "你已使用了超過此武器的上限使用次數! 此物品將從你的背包移除");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You cannot stab yourself"), "你不能刺你自己");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just stabbed <User> with a <Weapon>"), "<User> 剛剛使用 <Weapon> 刺了 <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just stabbed <User> with a <Weapon> and died"), "<User> 剛剛使用 <Weapon> 刺了 <User> 並死亡了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just stabbed <User> with an <Weapon>"), "<User> 剛剛使用 <Weapon> 刺了 <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> Just stabbed <User> with an <Weapon> and died"), "<User> 剛剛使用 <Weapon> 刺了 <User> 並死亡了");
