LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You can only bet once"), "You can only bet once");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "I have sent you bet list"), "I have sent you bet list");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Failed to send bet list, do you have your dms off?"), "Failed to send bet list, do you have your dms off?");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Pick where you want to place your chip. Type cancel to cancel. (You have 10 seconds to pick where you want to place it)"), "Pick where you want to place your chip. Type cancel to cancel. (You have 10 seconds to pick where you want to place it)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You did not pick where you want to place your chip on time."), "You did not pick where you want to place your chip on time.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Bet is incorrect. Please cancel your bet and do <RCommand>bets to check what bets you can and cannot do"), "Bet is incorrect. Please cancel your bet and do <RCommand>bets to check what bets you can and cannot do");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have canceled your bet"), "You have canceled your bet");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Joining Game"), "Joining Game");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Starting game in <Seconds> seconds"), "Starting game in <Seconds> seconds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Spinning..."), "Spinning...");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Rolled Black <Number>"), "Rolled Black <Number>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Rolled Red <Number>"), "Rolled Red <Number>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Roulette Wins"), "Roulette Wins");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "The minium withdrawal is <Amount>"), "The minium withdrawal is <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have enough to withdrawal <Bal>, You only have <Bank>"), "You do not have enough to withdrawal <Bal>, You only have <Bank>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**Money Withdrawn**\n\nYou just withdrawn <Bal> from your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank"), "**Money Withdrawn**\n\nYou just withdrawn <Bal> from your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You can use their Username, Display Name, Or tag"), "You can use their Username, Display Name, Or tag");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> chewed on <User>!"), "<User> chewed on <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> started turning red?"), "<User> started turning red?");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> started crying ;("), "<User> started crying ;(");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> started cuddling with <User>! (≧ヘ≦)"), "<User> started cuddling with <User>! (≧ヘ≦)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> started dancing!"), "<User> started dancing!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> hugged <User>!"), "<User> hugged <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> kissed <User>!"), "<User> kissed <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> licked <User>!"), "<User> licked <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> started patting <User>"), "<User> started patting <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> poked <User>!"), "<User> poked <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> punched <User>! :("), "<User> punched <User>! :(");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> slapped <User>!"), "<User> slapped <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> is getting tired."), "<User> is getting tired.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> has a smug look on their face >:)"), "<User> has a smug look on their face >:)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> is staring at <User>!"), "<User> is staring at <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> started tickling <User>!"), "<User> started tickling <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Image provided by <Provider>"), "Image provided by <Provider>");
