LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Rem Info"), "Rem Info");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Discord Server"), "Discord Server");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Lead Dev"), "Lead Dev");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Version"), "Version");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Servers"), "Servers");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Memory Usage"), "Memory Usage");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Website"), "Website");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Made With"), "Made With");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Discord.Net"), "Discord.Net");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Day> days, <Hour> hours, <Minute> minutes, <Second> seconds"), "<Day> days, <Hour> hours, <Minute> minutes, <Second> seconds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Uptime"), "Uptime");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Shard <Shard>"), "Shard <Shard>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Open Database Connections: <Connections>"), "Open Database Connections: <Connections>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**API Latency** <APILatency>ms\n**Bot Latency** <BotLatency>ms"), "**API Latency** <APILatency>ms\n**Bot Latency** <BotLatency>ms");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Ping Result"), "Ping Result");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have successfully sent your report to the admins"), "You have successfully sent your report to the admins");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Thank you for your suggestion!"), "Thank you for your suggestion!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Cash"), "Cash");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Bank"), "Bank");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Net Worth"), "Net Worth");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "BLACKJACK"), "BLACKJACK");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Your Cards"), "Your Cards");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Dealers Cards"), "Dealers Cards");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "BUST"), "BUST");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "WIN"), "WIN");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "PUSH"), "PUSH");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "LOSS"), "LOSS");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Value: <Value>"), "Value: <Value>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Level"), "Level");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "XP"), "XP");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Health"), "Health");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Bounty"), "Bounty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Winners"), "Winners");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Losers"), "Losers");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Romaji Title"), "Romaji Title");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Status"), "Status");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Episodes"), "Episodes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Unkown"), "Unkown");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Air Date"), "Air Date");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Average Score"), "Average Score");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Genres"), "Genres");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "null"), "null");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Trailer"), "Trailer");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "This anime/manga is for adults. If you want to view it you need to be in an nsfw channel"), "This anime/manga is for adults. If you want to view it you need to be in an nsfw channel");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Cannot find anime with title <Anime>"), "Cannot find anime with title <Anime>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Users>'s Avatar!"), "<Users>'s Avatar!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Invalid Args"), "Invalid Args");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please give valid letters to send"), "Please give valid letters to send");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Content is to long, Message needs to be under 2000 characters."), "Content is to long, Message needs to be under 2000 characters.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "It is certain"), "It is certain");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "It is decidedly so"), "It is decidedly so");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Without a doubt"), "Without a doubt");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Yes definitely"), "Yes definitely");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You may rely on it"), "You may rely on it");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "As I see it yes"), "As I see it yes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Most likely"), "Most likely");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Outlook good"), "Outlook good");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Yes"), "Yes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Signs point to yes"), "Signs point to yes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Reply hazy try again"), "Reply hazy try again");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Ask again later"), "Ask again later");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Better not tell you now"), "Better not tell you now");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Cannot predict now"), "Cannot predict now");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Concentrate and ask again"), "Concentrate and ask again");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Don't count on it"), "Don't count on it");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "My reply is no"), "My reply is no");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "My sources say no"), "My sources say no");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Outlook not so good"), "Outlook not so good");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Very doubtful"), "Very doubtful");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Question <Question>"), "Question <Question>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Answer <Answer>"), "Answer <Answer>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Coinflip"), "Coinflip");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "The coin landed on Heads"), "The coin landed on Heads");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "The coin landed on Tails"), "The coin landed on Tails");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Cannot find anime with genre <Genre> and year <Year>"), "Cannot find anime with genre <Genre> and year <Year>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Cannot find anime with year <Year>"), "Cannot find anime with year <Year>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Cannot find anime with genre <Genre>"), "Cannot find anime with genre <Genre>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Genre/Year is empty"), "Genre/Year is empty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Anime is empty"), "Anime is empty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "I do not have permission to delete messages"), "I do not have permission to delete messages");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Common Crate"), "Common Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Uncommon Crate"), "Uncommon Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Rare Crate"), "Rare Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Legendary Crate"), "Legendary Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Mythic Crate"), "Mythic Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**Common Winnings**"), "**Common Winnings**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**Uncommon Winnings**"), "**Uncommon Winnings**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**Rare Winnings**"), "**Rare Winnings**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**Legendary Winnings**"), "**Legendary Winnings**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**Mythic Winnings**"), "**Mythic Winnings**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Price"), "Price");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Common Odds"), "Common Odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Uncommon Odds"), "Uncommon Odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Rare odds"), "Rare odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Legendary Odds"), "Legendary Odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Mythic Odds"), "Mythic Odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Type"), "Type");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Rarity"), "Rarity");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Uses"), "Uses");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Damage"), "Damage");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Can Open"), "Can Open");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Kills"), "Kills");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Deaths"), "Deaths");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "K/D Ratio"), "K/D Ratio");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Damage Done"), "Damage Done");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Won From Gambling"), "Won From Gambling");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Lost From Gambling"), "Lost From Gambling");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Failed to get stats"), "Failed to get stats");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Statistic must be an Item, Crate, or a User"), "Statistic must be an Item, Crate, or a User");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You can only use nsfw commands in nsfw channels"), "You can only use nsfw commands in nsfw channels");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Lewd Neko"), "Lewd Neko");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Rem Lewd"), "Rem Lewd");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Thicc Thighs"), "Thicc Thighs");
