LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received an <Crate> Crate"), "你已領取你的投票禮物并獲取一個<Crate>寶箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received a <Crate> Crate"), "你已領取你的投票禮物并獲取一個<Crate>寶箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have claimed your voting gift"), "你已領取你的投票禮物");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received an <Prize>"), "你已領取你的投票禮物并獲取一個一份 <Prize>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received a <Prize>"), "你已領取你的投票禮物并獲取一個一份 <Prize>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You bought a winning lottery ticket and won <Amount>"), "你已購買一個贏的彩票並獲得金額<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You found a wallet on the ground that contained <Amount>"), "你在地上找到一個錢包裏面擁有<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You worked at the grocery store and earned <Amount>"), "你在雜貨店工作並獲得人工<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You streamed your \"amazing\" content on Twitch and made <Amount>"), "你在Twitch上直播你\"有趣\"的内容並獲得贊助金額<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You went to work as a plumber and earned <Amount>"), "你以水管工人的身份工作并獲得人工<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "On your way to work you got in a car accident and had to pay <Amount> for the damages"), "在你開車上班的途中，你遇上你交通意外並需要支付<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You went to your local grocery store and stole <Amount> from the cash register"), "你前往你本地的雜貨店並從收銀機偷取<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You found a homeless man on the street. You took all of his possessions and sold it for <Amount>>"), "你在街上找到一位露宿者，你拿取他所有的財產並以<Amount>售出");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You went to church and stole <Amount> from the donation basket"), "你去了教堂並從捐獻箱偷取了<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You found a homeless man on the street. When you attempted to rob him he pulled out his badge and fined you <Amount>"), "你在街上找到一位露宿者，當你嘗試去搶劫他的時候，他拿出他的警察徽章並向你罰款<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You attempted to rob an old lady, but she robbed you instead for <Amount>"), "你嘗試去搶劫一位老女士，她反而搶劫你並向你索取<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You went to your local grocery store attempted to rob it, You were caught by the security guard and fined <Amount>"), "你前往你本地的雜貨店並嘗試搶劫，不幸地你被警衛抓到並罰款 <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "The minium desposit is <Amount>"), "最低存款的金額為<Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not have enough to deposit <Amount>, You only have <Bal>"), "你沒有足夠的金額去存款<Amount>, 你目前擁有<Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**Money Desposited**\n\nYou just deposited <Bal> in your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank"), "**金錢已存款**\n\n你剛剛存款了<Bal>去你的銀行\n\n你目前擁有<Bal>，並擁有<Bank>在你的銀行裏");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Server>'s Leaderboards"), "<Server>的排行榜");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "There are no leaderboards in <Server>"), "<Server>目前沒有排行榜");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**You Won**\n\nYou rolled a <Number> and won <Bal>"), "**你贏了**\n\n你骰出了<Number>并獲得<Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**You Lost**\n\nYou rolled a <Number> and lost <Bal>"), "**你輸了**\n\n你骰出了<Number>并失去了<Bal>");
