LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You did not reply in time"), "You did not reply in time");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Language> is not a valid language"), "<Language> is not a valid language");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "The servers language is already set to <Language>"), "The servers language is already set to <Language>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Language has been changed to <Language>"), "Language has been changed to <Language>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please pick the desired language"), "Please pick the desired language");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have 30 seconds to reply"), "You have 30 seconds to reply");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have not voted"), "You have not voted");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "If you have voted in the last 12 hours please wait a few minutes and try again. Click this link to vote <Link>"), "If you have voted in the last 12 hours please wait a few minutes and try again. Click this link to vote <Link>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have claimed your voting gift"), "You have claimed your voting gift");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received an <Item>"), "You claimed your gift for voting and received an <Item>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received a <Item>"), "You claimed your gift for voting and received a <Item>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received <Money>, The money you win has been increased due to your <Votes> votes"), "You claimed your gift for voting and received <Money>, The money you win has been increased due to your <Votes> votes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received <Money>"), "You claimed your gift for voting and received <Money>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received an <Crate> Crate, Your odds have been increased due to your <Votes> votes"), "You claimed your gift for voting and received an <Crate> Crate, Your odds have been increased due to your <Votes> votes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received a <Crate> Crate, Your odds have been increased due to your <Votes> votes"), "You claimed your gift for voting and received a <Crate> Crate, Your odds have been increased due to your <Votes> votes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received an <Crate> Crate"), "You claimed your gift for voting and received an <Crate> Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received a <Crate> Crate"), "You claimed your gift for voting and received a <Crate> Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have any extra gifts to claim"), "You do not have any extra gifts to claim");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", ":x: Be in the support server\n:x: Nitro boost the support server\n:x: Be a patreon supporter"), ":x: Be in the support server\n:x: Nitro boost the support server\n:x: Be a patreon supporter");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for being a <Role> and recieved"), "You claimed your gift for being a <Role> and recieved");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Claims"), "Claims");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "I have sent the command list to your direct messages"), "I have sent the command list to your direct messages");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Failed to send direct message. Check privacy settings and try again"), "Failed to send direct message. Check privacy settings and try again");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Command does not exist!"), "Command does not exist!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Aliases"), "Aliases");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Summary"), "Summary");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Suggestion cannot be empty"), "Suggestion cannot be empty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Report cannot be empty"), "Report cannot be empty");
