LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please give me a valid amount"), "Please give me a valid amount");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Amount must be a number"), "Amount must be a number");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Amount must be more than 0"), "Amount must be more than 0");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have enough to place a <Amount> bounty, You only have <Bal>"), "You do not have enough to place a <Amount> bounty, You only have <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Failed to parse bounty"), "Failed to parse bounty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You added <Amount> to <User>'s Bounty"), "You added <Amount> to <User>'s Bounty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Server> Top Bounties"), "<Server> Top Bounties");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "There are no bounties in  <Server>"), "There are no bounties in  <Server>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received an <Crate> Crate"), "You claimed your gift for voting and received an <Crate> Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received a <Crate> Crate"), "You claimed your gift for voting and received a <Crate> Crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have claimed your voting gift"), "You have claimed your voting gift");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received an <Prize>"), "You claimed your gift for voting and received an <Prize>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You claimed your gift for voting and received a <Prize>"), "You claimed your gift for voting and received a <Prize>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You bought a winning lottery ticket and won <Amount>"), "You bought a winning lottery ticket and won <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You found a wallet on the ground that contained <Amount>"), "You found a wallet on the ground that contained <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You worked at the grocery store and earned <Amount>"), "You worked at the grocery store and earned <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You streamed your \"amazing\" content on Twitch and made <Amount>"), "You streamed your \"amazing\" content on Twitch and made <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You went to work as a plumber and earned <Amount>"), "You went to work as a plumber and earned <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "On your way to work you got in a car accident and had to pay <Amount> for the damages"), "On your way to work you got in a car accident and had to pay <Amount> for the damages");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You went to your local grocery store and stole <Amount> from the cash register"), "You went to your local grocery store and stole <Amount> from the cash register");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You found a homeless man on the street. You took all of his possessions and sold it for <Amount>>"), "You found a homeless man on the street. You took all of his possessions and sold it for <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You went to church and stole <Amount> from the donation basket"), "You went to church and stole <Amount> from the donation basket");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You found a homeless man on the street. When you attempted to rob him he pulled out his badge and fined you <Amount>"), "You found a homeless man on the street. When you attempted to rob him he pulled out his badge and fined you <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You attempted to rob an old lady, but she robbed you instead for <Amount>"), "You attempted to rob an old lady, but she robbed you instead for <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You went to your local grocery store attempted to rob it, You were caught by the security guard and fined <Amount>"), "You went to your local grocery store attempted to rob it, You were caught by the security guard and fined <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "The minium desposit is <Amount>"), "The minium desposit is <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have enough to deposit <Amount>, You only have <Bal>"), "You do not have enough to deposit <Amount>, You only have <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**Money Desposited**\n\nYou just deposited <Bal> in your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank"), "**Money Desposited**\n\nYou just deposited <Bal> in your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Server>'s Leaderboards"), "<Server>'s Leaderboards");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "There are no leaderboards in <Server>"), "There are no leaderboards in <Server>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**You Won**\n\nYou rolled a <Number> and won <Bal>"), "**You Won**\n\nYou rolled a <Number> and won <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "**You Lost**\n\nYou rolled a <Number> and lost <Bal>"), "**You Lost**\n\nYou rolled a <Number> and lost <Bal>");
