LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Rem Info"), "Rem資訊");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Discord Server"), "Discord 伺服器");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Lead Dev"), "開發者");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Version"), "版本");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Servers"), "伺服器");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Memory Usage"), "記憶體使用量");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Website"), "網站");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Made With"), "使用");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Discord.Net"), "Discord.Net");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Day> days, <Hour> hours, <Minute> minutes, <Second> seconds"), "<Day> 日, <Hour> 時, <Minute> 分, <Second> 秒");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Uptime"), "上綫時間");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Shard <Shard>"), "碎片 <Shard>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Open Database Connections: <Connections>"), "數據庫連接: <Connections>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**API Latency** <APILatency>ms\n**Bot Latency** <BotLatency>ms"), "**API 延遲** <APILatency>ms\n**機械人 延遲** <BotLatency>ms");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Ping Result"), "Ping 結果");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have successfully sent your report to the admins"), "你已成功將報告傳送到管理員");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Thank you for your suggestion!"), "多謝你的建議!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Cash"), "現金");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Bank"), "銀行");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Net Worth"), "淨值");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "BLACKJACK"), "BLACKJACK");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Your Cards"), "你的手牌");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Dealers Cards"), "莊家的手牌");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "BUST"), "爆了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "WIN"), "贏");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "PUSH"), "推");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "LOSS"), "輸");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Value: <Value>"), "價值: <Value>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Level"), "等級");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "XP"), "XP");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Health"), "生命");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Bounty"), "賞金");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Winners"), "贏家");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Losers"), "輸家");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Romaji Title"), "羅馬標題");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Status"), "狀態");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Episodes"), "集數");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Unkown"), "不知");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Air Date"), "播出日期");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Average Score"), "平均分數");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Genres"), "體裁");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "null"), "null");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Trailer"), "預告片");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "This anime/manga is for adults. If you want to view it you need to be in an nsfw channel"), "此動漫/漫畫觀看對象為成人，如果你想觀看，你需要進入 NSFW 頻道");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Cannot find anime with title <Anime>"), "無法找到<Anime> 的動漫");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Users>'s Avatar!"), "<Users> 的頭像!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Invalid Args"), "無效的參數");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Please give valid letters to send"), "請提供有效的字母");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Content is to long, Message needs to be under 2000 characters."), "内容過長, 信息需要在2000字以下");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "It is certain"), "可以肯定的是");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "It is decidedly so"), "絕對是這樣");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Without a doubt"), "沒有懷疑");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Yes definitely"), "一定是");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You may rely on it"), "你可以信賴的");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "As I see it yes"), "依我看是");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Most likely"), "最有可能的");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Outlook good"), "前景良好");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Yes"), "是");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Signs point to yes"), "跡象表明顯示是");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Reply hazy try again"), "回答模糊，再試一次");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Ask again later"), "稍後再問");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Better not tell you now"), "最好現在不告訴你");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Cannot predict now"), "現在無法預測");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Concentrate and ask again"), "集中再問一次");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Don't count on it"), "不要指望它");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "My reply is no"), "我的答案是不");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "My sources say no"), "我的資源說不");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Outlook not so good"), "前景不太好");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Very doubtful"), "非常懷疑");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Question <Question>"), "問題 <Question>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Answer <Answer>"), "答案 <Answer>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Coinflip"), "砸公字");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "The coin landed on Heads"), "公");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "The coin landed on Tails"), "字");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Cannot find anime with genre <Genre> and year <Year>"), "無法使用類型 <Genre> 和年份 <Year> 找到動漫");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Cannot find anime with year <Year>"), "無法使用年份 <Year> 找到動漫");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Cannot find anime with genre <Genre>"), "無法使用類型 <Genre> 找到動漫");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Genre/Year is empty"), "類型/年份為空白");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Anime is empty"), "動漫是空白");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "I do not have permission to delete messages"), "我沒有權限去刪除信息");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Common Crate"), "常見箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Uncommon Crate"), "不常見箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Rare Crate"), "稀有箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Legendary Crate"), "傳説箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Mythic Crate"), "神秘箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**Common Winnings**"), "**常見禮品**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**Uncommon Winnings**"), "**不常見禮品**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**Rare Winnings**"), "**稀有禮品**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**Legendary Winnings**"), "**傳説禮品**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**Mythic Winnings**"), "**神秘禮品**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Price"), "價錢");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Common Odds"), "常見 Odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Uncommon Odds"), "不常見 Odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Rare odds"), "稀有 odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Legendary Odds"), "傳説 Odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Mythic Odds"), "神秘 Odds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Type"), "類型");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Rarity"), "稀有度");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Uses"), "使用了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Damage"), "傷害");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Can Open"), "可以開啟");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Kills"), "擊殺數");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Deaths"), "死亡數");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "K/D Ratio"), "K/D 比率");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Damage Done"), "傷害完成");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Won From Gambling"), "贏了賭博");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Lost From Gambling"), "輸了賭博");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Failed to get stats"), "不成功取得統計資料");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Statistic must be an Item, Crate, or a User"), "統計資料必須是一個物品,箱或用戶");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You can only use nsfw commands in nsfw channels"), "你只能在 NSFW 的頻道使用 NSFW 的指令");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Lewd Neko"), "Lewd Neko");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Rem Lewd"), "Rem Lewd");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Thicc Thighs"), "Thicc Thighs");
