LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Number is too big!"), "Number is too big!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Amount is too large"), "Amount is too large");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please give me a valid crate"), "Please give me a valid crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Amount cannot be less than 1"), "Amount cannot be less than 1");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Crate> crate does not exist"), "<Crate> crate does not exist");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Current crates: Mythic, Legendary, Rare, Uncommon, Common"), "Current crates: Mythic, Legendary, Rare, Uncommon, Common");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Crate> is not for sale"), "<Crate> is not for sale");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have enough money to buy <Amount> <Crate> crates\n\nYou need <NeededAmount>"), "You do not have enough money to buy <Amount> <Crate> crates\n\nYou need <NeededAmount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have enough money to buy <Amount> <Crate> crate\n\nYou need <NeededAmount>"), "You do not have enough money to buy <Amount> <Crate> crate\n\nYou need <NeededAmount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You cannot have more than 999,999,999 crates"), "You cannot have more than 999,999,999 crates");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You just bought <Amount> <Crate> crates"), "You just bought <Amount> <Crate> crates");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You just bought <Amount> <Crate> crate"), "You just bought <Amount> <Crate> crate");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please give me a valid Amount/Item"), "Please give me a valid Amount/Item");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You can't donate to yourself"), "You can't donate to yourself");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Failed to parse string"), "Failed to parse string");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have enough money to donate <Amount> You only have <Bal>"), "You do not have enough money to donate <Amount> You only have <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have successfully given <User> <Amount>"), "You have successfully given <User> <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Give me a valid food name"), "Give me a valid food name");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You are already at the max health <MaxHealth>"), "You are already at the max health <MaxHealth>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You just ate an <Food> and you are now at <Health>"), "You just ate an <Food> and you are now at <Health>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You just ate a <Food> and you are now at <Health>"), "You just ate a <Food> and you are now at <Health>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have <Owned> <Food> left"), "You have <Owned> <Food> left");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You just went fishing and came back with a <Food>"), "You just went fishing and came back with a <Food>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You just went fishing and came back with an <Food>"), "You just went fishing and came back with an <Food>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You just caught a <Food> in the wilderness"), "You just caught a <Food> in the wilderness");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You just caught an <Food> in the wilderness"), "You just caught an <Food> in the wilderness");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have anything in your inventory"), "You do not have anything in your inventory");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "They do not have anything in their inventory"), "They do not have anything in their inventory");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You can only open 10 crates at a time"), "You can only open 10 crates at a time");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not own any <Crate> crates"), "You do not own any <Crate> crates");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have enough crates to open <Amount>, you only have <Owned>"), "You do not have enough crates to open <Amount>, you only have <Owned>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please give me a valid weapon"), "Please give me a valid weapon");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You cannot shoot yourself"), "You cannot shoot yourself");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Weapon> does not exist"), "<Weapon> does not exist");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not own any <Weapon>'s"), "You do not own any <Weapon>'s");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "This weapon is a knife, Not a gun"), "This weapon is a knife, Not a gun");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "To use this weapon appropriately use <Shoot>"), "To use this weapon appropriately use <Shoot>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Health Before"), "Health Before");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Health After"), "Health After");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Money Lost"), "Money Lost");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You cannot have more than the max bal in your wallet"), "You cannot have more than the max bal in your wallet");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "The weapon has reached max uses and has been destroyed"), "The weapon has reached max uses and has been destroyed");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You have been killed"), "You have been killed");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "User that killed you"), "User that killed you");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just took 50% of your money <MoneyTaken>"), "<User> Just took 50% of your money <MoneyTaken>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> had a bounty of <Bounty> and it has been collected by <User>"), "<User> had a bounty of <Bounty> and it has been collected by <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just shot <User> with a <Weapon>"), "<User> Just shot <User> with a <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just shot <User> with a <Weapon> and died"), "<User> Just shot <User> with a <Weapon> and died");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just shot <User> with an <Weapon>"), "<User> Just shot <User> with an <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just shot <User> with an <Weapon> and died"), "<User> Just shot <User> with an <Weapon> and died");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You used this weapon more than it's intended use! This weapon has been deleted from your inventory"), "You used this weapon more than it's intended use! This weapon has been deleted from your inventory");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You cannot stab yourself"), "You cannot stab yourself");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just stabbed <User> with a <Weapon>"), "<User> Just stabbed <User> with a <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just stabbed <User> with a <Weapon> and died"), "<User> Just stabbed <User> with a <Weapon> and died");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just stabbed <User> with an <Weapon>"), "<User> Just stabbed <User> with an <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> Just stabbed <User> with an <Weapon> and died"), "<User> Just stabbed <User> with an <Weapon> and died");
