LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You can only bet once"), "你只可以賭注一次");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "I have sent you bet list"), "我已經將賭注列表傳送");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Failed to send bet list, do you have your dms off?"), "不能成功傳送賭注列表，你是是否關閉了私人對話?");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Pick where you want to place your chip. Type cancel to cancel. (You have 10 seconds to pick where you want to place it)"), "選擇你想在哪裏放下你的籌碼，輸入cancel 去取消. (你有 10 秒時間去選擇)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You did not pick where you want to place your chip on time."), "你沒有在指定時間内選擇你想在哪裏放下你的籌碼");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Bet is incorrect. Please cancel your bet and do <RCommand>bets to check what bets you can and cannot do"), "賭注錯誤. 請取消你的賭注并執行 <RCommand> 賭注去檢查你有甚麼賭注可以哪些不能");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have canceled your bet"), "你已取消你的賭注");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Joining Game"), "加入遊戲中");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Starting game in <Seconds> seconds"), "遊戲將於 <Seconds> 秒開始");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Spinning..."), "轉動中...");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Rolled Black <Number>"), "轉出了黑色數字 <Number>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Rolled Red <Number>"), "轉出了紅色數字 <Number>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Roulette Wins"), "贏了輪盤");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "The minium withdrawal is <Amount>"), "最低需要提款額為 <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not have enough to withdrawal <Bal>, You only have <Bank>"), "你沒有足夠的金錢去提款 <Bal>, 你只有 <Bank>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "**Money Withdrawn**\n\nYou just withdrawn <Bal> from your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank"), "**金錢提款**\n\n你剛剛從你的銀行提款 <Bal> \n\n你的錢包現在擁有 <Bal>  和 <Bank> 在你的銀行");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You can use their Username, Display Name, Or tag"), "你可以使用他們的名字, 顯示的名稱, 或 標籤");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> chewed on <User>!"), "<User> 咬了 <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> started turning red?"), "<User> 開始變紅了?");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> started crying ;("), "<User> 開始哭了 ;(");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> started cuddling with <User>! (≧ヘ≦)"), "<User> 開始與 <User> 擁抱! (≧ヘ≦)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> started dancing!"), "<User> 開始跳舞!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> hugged <User>!"), "<User> 抱 <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> kissed <User>!"), "<User> 親 <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> licked <User>!"), "<User> 舔 <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> started patting <User>"), "<User> 拍了 <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> poked <User>!"), "<User> 戳 <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> punched <User>! :("), "<User> 打了 <User>! :(");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> slapped <User>!"), "<User> 刮了 <User> 巴掌!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> is getting tired."), "<User> 覺得有些少疲倦");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> has a smug look on their face >:)"), "<User> 臉上露出飄飄然樣子 >:)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> is staring at <User>!"), "<User> 對 <User> 對視著!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<User> started tickling <User>!"), "<User> 對 <User> 開始搔癢!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Image provided by <Provider>"), "圖片由 <Provider> 提供");
