LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You did not reply in time"), "你沒有在指定時間内回覆");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Language> is not a valid language"), "<Language> 不是有效的語言");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "The servers language is already set to <Language>"), "伺服器的語言已經設定為 <Language>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Language has been changed to <Language>"), "語言已設定為 <Language>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Please pick the desired language"), "請選擇一個語言");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have 30 seconds to reply"), "你有30秒時間回覆");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have not voted"), "你沒有投票");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "If you have voted in the last 12 hours please wait a few minutes and try again. Click this link to vote <Link>"), "如果你在剛剛12小時内投過票，請你稍侯再試。 按此投票 <Link>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You have claimed your voting gift"), "你已領取你的投票禮包");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received an <Item>"), "你已領取你的投票禮包並獲得 <Item>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received a <Item>"), "你已領取你的投票禮包並獲得 <Item>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received <Money>, The money you win has been increased due to your <Votes> votes"), "你已領取你的投票禮包並獲得 <Money>, 因爲你的<Votes>次投票，你的金錢增加了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received <Money>"), "你已領取你的投票禮包並獲得 <Money>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received an <Crate> Crate, Your odds have been increased due to your <Votes> votes"), "你已領取你的投票禮包並獲得一個 <Crate> 箱子, 因爲你的<Votes>次投票，你的機會增加了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received a <Crate> Crate, Your odds have been increased due to your <Votes> votes"), "你已領取你的投票禮包並獲得一個 <Crate> 箱子, 因爲你的<Votes>次投票，你的機會增加了");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received an <Crate> Crate"), "你已領取你的投票禮包並獲得一個 <Crate> 箱子);
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for voting and received a <Crate> Crate"), "你已領取你的投票禮包並獲得一個 <Crate> 箱子");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You do not have any extra gifts to claim"), "你沒有額外的禮包可以領取");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", ":x: Be in the support server\n:x: Nitro boost the support server\n:x: Be a patreon supporter"), ":x: 成為了贊助者\n:x: Nitro boost 了贊助了伺服器\n:x: 成為patreon的贊助者");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You claimed your gift for being a <Role> and recieved"), "你成為了<Role>並已領取你的禮包");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Claims"), "Claims");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "I have sent the command list to your direct messages"), "我已經將指令透過私聊給了你");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Failed to send direct message. Check privacy settings and try again"), "傳送私聊失敗，請查看你的私隱設定");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Command does not exist!"), "無效的指令!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Aliases"), "別名");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Summary"), "總結");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Suggestion cannot be empty"), "建議不能為空的");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Report cannot be empty"), "投訴不能為空的");
