LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Bets"), "下注");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You need to ask Rem a question for a prediction"), "你需要問雷姆一個問題才能預測");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "You need the `Manage Messages` permission on this channel to use this command"), "你需要在此頻道擁有 `Manage Messages` 的權限才能使用此指令");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Please give me a message to repeat"), "請給我一句信息去重複");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Weapons"), "武器");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Crates"), "箱");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Food"), "食物");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Weapon> Owned: <Amount> Uses: <Uses>"), "<Weapon> 擁有數量: <Amount> 使用: <Uses>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "<Type> Owned: <Amount>"), "<Type> 擁有: <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "This weapon is a gun, not a knife"), "此物品是槍, 不是刀");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Common"), "常見");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Uncommon"), "不常見");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Rare"), "稀有");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Legendary"), "傳説");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Mythic"), "神秘");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Gun"), "槍");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Traditional Chinese", "Knife"), "刀");
