LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You need the `Administrator` permission to use this command"), "You need the `Administrator` permission to use this command");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Currency cannot be empty"), "Currency cannot be empty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Currency is too large, It must be under 30 characters"), "Currency is too large, It must be under 30 characters");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Emote not parsed, Emote must be in the current server and needs to be custom."), "Emote not parsed, Emote must be in the current server and needs to be custom.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You cannot use default discord emojis!"), "You cannot use default discord emojis!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Currency changed to <Currency>"), "Currency changed to <Currency>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<Option> has been reset"), "<Option> has been reset");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please be consistent with the user you're choosing"), "Please be consistent with the user you're choosing");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Failed to get user"), "Failed to get user");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "If you are attempting to reset the server please do not give any arguments. If you are trying to reset a user give me a valid user"), "If you are attempting to reset the server please do not give any arguments. If you are trying to reset a user give me a valid user");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You are attempting to reset <Server>, This will reset every person in this guild, Please use this command again to continue. Command will expire in 10 seconds"), "You are attempting to reset <Server>, This will reset every person in this guild, Please use this command again to continue. Command will expire in 10 seconds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You are attempting to reset <User>, This will only reset <User> and no one else, Please use this command again to continue. Command will expire in 10 seconds"), "You are attempting to reset <User>, This will only reset <User> and no one else, Please use this command again to continue. Command will expire in 10 seconds");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Prefix cannot be empty"), "Prefix cannot be empty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Prefix cannot be more than 8 characters"), "Prefix cannot be more than 8 characters");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You cannot change the prefix to <Prefix> the prefix is already <Prefix>"), "You cannot change the prefix to <Prefix> the prefix is already <Prefix>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Prefix has been changed to <Prefix>"), "Prefix has been changed to <Prefix>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have permission to use this command"), "You do not have permission to use this command");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You need the Manage Guild permission to use this command"), "You need the Manage Guild permission to use this command");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You must be a Legendary Supporter or higher on our Patreon"), "You must be a Legendary Supporter or higher on our Patreon");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please give me a valid Reason"), "Please give me a valid Reason");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Please give me a valid user (User cannot be a bot)"), "Please give me a valid user (User cannot be a bot)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Failed to parse balance"), "Failed to parse balance");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You can not add more than <Bal>"), "You can not add more than <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> just gave <Bal> to <User>"), "<User> just gave <Bal> to <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "<User> just gave <Bal> to <User> for <Reason>"), "<User> just gave <Bal> to <User> for <Reason>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Amount must be a number or equal 'all'"), "Amount must be a number or equal 'all'");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "The minium gamble is <Amount>"), "The minium gamble is <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You do not have enough to gamble <Bal>, You only have <Bal>"), "You do not have enough to gamble <Bal>, You only have <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You Won You rolled a <Number> and won <Bal>"), "You Won You rolled a <Number> and won <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You Lost You rolled a <Number> and lost <Bal>"), "You Lost You rolled a <Number> and lost <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Couldn't find user, If this problem countinues ping them"), "Couldn't find user, If this problem countinues ping them");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "There is a timeout on this command"), "There is a timeout on this command");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You can use this command in <Timeout>"), "You can use this command in <Timeout>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Failed to parse bal/bank"), "Failed to parse bal/bank");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Type hit to draw another card, or stand/stay to stand."), "Type hit to draw another card, or stand/stay to stand.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "If you do not pick a choice in <Time> seconds it will stand for you"), "If you do not pick a choice in <Time> seconds it will stand for you");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "You did not lose any money."), "You did not lose any money.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Money won <Amount>"), "Money won <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("English", "Money lost <Amount>"), "Money lost <Amount>");
